import streamlit as st


ELEMENTS = [
    {"number": 1, "symbol": "H", "row": 1, "column": 1, "category": "nonmetal"},
    {"number": 2, "symbol": "He", "row": 1, "column": 18, "category": "noble"},
    {"number": 3, "symbol": "Li", "row": 2, "column": 1, "category": "alkali"},
    {"number": 4, "symbol": "Be", "row": 2, "column": 2, "category": "alkaline-earth"},
    {"number": 5, "symbol": "B", "row": 2, "column": 13, "category": "metalloid"},
    {"number": 6, "symbol": "C", "row": 2, "column": 14, "category": "nonmetal"},
    {"number": 7, "symbol": "N", "row": 2, "column": 15, "category": "nonmetal"},
    {"number": 8, "symbol": "O", "row": 2, "column": 16, "category": "nonmetal"},
    {"number": 9, "symbol": "F", "row": 2, "column": 17, "category": "nonmetal"},
    {"number": 10, "symbol": "Ne", "row": 2, "column": 18, "category": "noble"},
    {"number": 11, "symbol": "Na", "row": 3, "column": 1, "category": "alkali"},
    {"number": 12, "symbol": "Mg", "row": 3, "column": 2, "category": "alkaline-earth"},
    {"number": 13, "symbol": "Al", "row": 3, "column": 13, "category": "post-transition"},
    {"number": 14, "symbol": "Si", "row": 3, "column": 14, "category": "metalloid"},
    {"number": 15, "symbol": "P", "row": 3, "column": 15, "category": "nonmetal"},
    {"number": 16, "symbol": "S", "row": 3, "column": 16, "category": "nonmetal"},
    {"number": 17, "symbol": "Cl", "row": 3, "column": 17, "category": "nonmetal"},
    {"number": 18, "symbol": "Ar", "row": 3, "column": 18, "category": "noble"},
    {"number": 19, "symbol": "K", "row": 4, "column": 1, "category": "alkali"},
    {"number": 20, "symbol": "Ca", "row": 4, "column": 2, "category": "alkaline-earth"},
    {"number": 21, "symbol": "Sc", "row": 4, "column": 3, "category": "transition"},
    {"number": 22, "symbol": "Ti", "row": 4, "column": 4, "category": "transition"},
    {"number": 23, "symbol": "V", "row": 4, "column": 5, "category": "transition"},
    {"number": 24, "symbol": "Cr", "row": 4, "column": 6, "category": "transition"},
    {"number": 25, "symbol": "Mn", "row": 4, "column": 7, "category": "transition"},
    {"number": 26, "symbol": "Fe", "row": 4, "column": 8, "category": "transition"},
    {"number": 27, "symbol": "Co", "row": 4, "column": 9, "category": "transition"},
    {"number": 28, "symbol": "Ni", "row": 4, "column": 10, "category": "transition"},
    {"number": 29, "symbol": "Cu", "row": 4, "column": 11, "category": "transition"},
    {"number": 30, "symbol": "Zn", "row": 4, "column": 12, "category": "transition"},
    {"number": 31, "symbol": "Ga", "row": 4, "column": 13, "category": "post-transition"},
    {"number": 32, "symbol": "Ge", "row": 4, "column": 14, "category": "metalloid"},
    {"number": 33, "symbol": "As", "row": 4, "column": 15, "category": "metalloid"},
    {"number": 34, "symbol": "Se", "row": 4, "column": 16, "category": "nonmetal"},
    {"number": 35, "symbol": "Br", "row": 4, "column": 17, "category": "nonmetal"},
    {"number": 36, "symbol": "Kr", "row": 4, "column": 18, "category": "noble"},
    {"number": 37, "symbol": "Rb", "row": 5, "column": 1, "category": "alkali"},
    {"number": 38, "symbol": "Sr", "row": 5, "column": 2, "category": "alkaline-earth"},
    {"number": 39, "symbol": "Y", "row": 5, "column": 3, "category": "transition"},
    {"number": 40, "symbol": "Zr", "row": 5, "column": 4, "category": "transition"},
    {"number": 41, "symbol": "Nb", "row": 5, "column": 5, "category": "transition"},
    {"number": 42, "symbol": "Mo", "row": 5, "column": 6, "category": "transition"},
    {"number": 43, "symbol": "Tc", "row": 5, "column": 7, "category": "transition"},
    {"number": 44, "symbol": "Ru", "row": 5, "column": 8, "category": "transition"},
    {"number": 45, "symbol": "Rh", "row": 5, "column": 9, "category": "transition"},
    {"number": 46, "symbol": "Pd", "row": 5, "column": 10, "category": "transition"},
    {"number": 47, "symbol": "Ag", "row": 5, "column": 11, "category": "transition"},
    {"number": 48, "symbol": "Cd", "row": 5, "column": 12, "category": "transition"},
    {"number": 49, "symbol": "In", "row": 5, "column": 13, "category": "post-transition"},
    {"number": 50, "symbol": "Sn", "row": 5, "column": 14, "category": "post-transition"},
    {"number": 51, "symbol": "Sb", "row": 5, "column": 15, "category": "metalloid"},
    {"number": 52, "symbol": "Te", "row": 5, "column": 16, "category": "metalloid"},
    {"number": 53, "symbol": "I", "row": 5, "column": 17, "category": "nonmetal"},
    {"number": 54, "symbol": "Xe", "row": 5, "column": 18, "category": "noble"},
    {"number": 55, "symbol": "Cs", "row": 6, "column": 1, "category": "alkali"},
    {"number": 56, "symbol": "Ba", "row": 6, "column": 2, "category": "alkaline-earth"},
    {"number": 57, "symbol": "La", "row": 8, "column": 3, "category": "lanthanide"},
    {"number": 58, "symbol": "Ce", "row": 8, "column": 4, "category": "lanthanide"},
    {"number": 59, "symbol": "Pr", "row": 8, "column": 5, "category": "lanthanide"},
    {"number": 60, "symbol": "Nd", "row": 8, "column": 6, "category": "lanthanide"},
    {"number": 61, "symbol": "Pm", "row": 8, "column": 7, "category": "lanthanide"},
    {"number": 62, "symbol": "Sm", "row": 8, "column": 8, "category": "lanthanide"},
    {"number": 63, "symbol": "Eu", "row": 8, "column": 9, "category": "lanthanide"},
    {"number": 64, "symbol": "Gd", "row": 8, "column": 10, "category": "lanthanide"},
    {"number": 65, "symbol": "Tb", "row": 8, "column": 11, "category": "lanthanide"},
    {"number": 66, "symbol": "Dy", "row": 8, "column": 12, "category": "lanthanide"},
    {"number": 67, "symbol": "Ho", "row": 8, "column": 13, "category": "lanthanide"},
    {"number": 68, "symbol": "Er", "row": 8, "column": 14, "category": "lanthanide"},
    {"number": 69, "symbol": "Tm", "row": 8, "column": 15, "category": "lanthanide"},
    {"number": 70, "symbol": "Yb", "row": 8, "column": 16, "category": "lanthanide"},
    {"number": 71, "symbol": "Lu", "row": 8, "column": 17, "category": "lanthanide"},
    {"number": 72, "symbol": "Hf", "row": 6, "column": 4, "category": "transition"},
    {"number": 73, "symbol": "Ta", "row": 6, "column": 5, "category": "transition"},
    {"number": 74, "symbol": "W", "row": 6, "column": 6, "category": "transition"},
    {"number": 75, "symbol": "Re", "row": 6, "column": 7, "category": "transition"},
    {"number": 76, "symbol": "Os", "row": 6, "column": 8, "category": "transition"},
    {"number": 77, "symbol": "Ir", "row": 6, "column": 9, "category": "transition"},
    {"number": 78, "symbol": "Pt", "row": 6, "column": 10, "category": "transition"},
    {"number": 79, "symbol": "Au", "row": 6, "column": 11, "category": "transition"},
    {"number": 80, "symbol": "Hg", "row": 6, "column": 12, "category": "transition"},
    {"number": 81, "symbol": "Tl", "row": 6, "column": 13, "category": "post-transition"},
    {"number": 82, "symbol": "Pb", "row": 6, "column": 14, "category": "post-transition"},
    {"number": 83, "symbol": "Bi", "row": 6, "column": 15, "category": "post-transition"},
    {"number": 84, "symbol": "Po", "row": 6, "column": 16, "category": "unknown"},
    {"number": 85, "symbol": "At", "row": 6, "column": 17, "category": "nonmetal"},
    {"number": 86, "symbol": "Rn", "row": 6, "column": 18, "category": "noble"},
    {"number": 87, "symbol": "Fr", "row": 7, "column": 1, "category": "alkali"},
    {"number": 88, "symbol": "Ra", "row": 7, "column": 2, "category": "alkaline-earth"},
    {"number": 89, "symbol": "Ac", "row": 9, "column": 3, "category": "actinide"},
    {"number": 90, "symbol": "Th", "row": 9, "column": 4, "category": "actinide"},
    {"number": 91, "symbol": "Pa", "row": 9, "column": 5, "category": "actinide"},
    {"number": 92, "symbol": "U", "row": 9, "column": 6, "category": "actinide"},
    {"number": 93, "symbol": "Np", "row": 9, "column": 7, "category": "actinide"},
    {"number": 94, "symbol": "Pu", "row": 9, "column": 8, "category": "actinide"},
    {"number": 95, "symbol": "Am", "row": 9, "column": 9, "category": "actinide"},
    {"number": 96, "symbol": "Cm", "row": 9, "column": 10, "category": "actinide"},
    {"number": 97, "symbol": "Bk", "row": 9, "column": 11, "category": "actinide"},
    {"number": 98, "symbol": "Cf", "row": 9, "column": 12, "category": "actinide"},
    {"number": 99, "symbol": "Es", "row": 9, "column": 13, "category": "actinide"},
    {"number": 100, "symbol": "Fm", "row": 9, "column": 14, "category": "actinide"},
    {"number": 101, "symbol": "Md", "row": 9, "column": 15, "category": "actinide"},
    {"number": 102, "symbol": "No", "row": 9, "column": 16, "category": "actinide"},
    {"number": 103, "symbol": "Lr", "row": 9, "column": 17, "category": "actinide"},
    {"number": 104, "symbol": "Rf", "row": 7, "column": 4, "category": "transition"},
    {"number": 105, "symbol": "Db", "row": 7, "column": 5, "category": "transition"},
    {"number": 106, "symbol": "Sg", "row": 7, "column": 6, "category": "transition"},
    {"number": 107, "symbol": "Bh", "row": 7, "column": 7, "category": "transition"},
    {"number": 108, "symbol": "Hs", "row": 7, "column": 8, "category": "transition"},
    {"number": 109, "symbol": "Mt", "row": 7, "column": 9, "category": "transition"},
    {"number": 110, "symbol": "Ds", "row": 7, "column": 10, "category": "transition"},
    {"number": 111, "symbol": "Rg", "row": 7, "column": 11, "category": "transition"},
    {"number": 112, "symbol": "Cn", "row": 7, "column": 12, "category": "unknown"},
    {"number": 113, "symbol": "Nh", "row": 7, "column": 13, "category": "post-transition"},
    {"number": 114, "symbol": "Fl", "row": 7, "column": 14, "category": "post-transition"},
    {"number": 115, "symbol": "Mc", "row": 7, "column": 15, "category": "post-transition"},
    {"number": 116, "symbol": "Lv", "row": 7, "column": 16, "category": "post-transition"},
    {"number": 117, "symbol": "Ts", "row": 7, "column": 17, "category": "unknown"},
    {"number": 118, "symbol": "Og", "row": 7, "column": 18, "category": "noble"},
]


def render_periodic_table(
    on_element_click,
    selected_symbols=None,
    available_symbols=None,
    key_prefix="periodic-table",
):
    selected_symbols = set(selected_symbols or [])
    available_symbols = None if available_symbols is None else set(available_symbols)
    element_map = {(element["row"], element["column"]): element for element in ELEMENTS}

    for row_number in range(1, 10):
        columns = st.columns(18, gap="small")
        for column_number, column in enumerate(columns, start=1):
            element = element_map.get((row_number, column_number))
            if element is None:
                column.write("")
                continue

            column.button(
                element["symbol"],
                key=f"{key_prefix}-{element['number']}",
                width="stretch",
                on_click=on_element_click,
                args=(element["symbol"],),
                type="primary" if element["symbol"] in selected_symbols else "secondary",
                disabled=available_symbols is not None
                and element["symbol"] not in available_symbols,
            )
